### ISSUE TITLE
This looks dope

### ISSUE THREAD

**Issue by urmilshroff** [SwagLyrics/autosynch#11]
Does it work properly? And can it keep up with Rap God? 😂

**Comment by aadibajpai** [comment]
> Does it work properly? And can it keep up with Rap God? 😂

It depends on the song, there are a few known cases that affect synchronization (imperfect vocal isolation or a mislabelled section) that need to be improved but there are some songs where they're up to a sing-alongable standard. 

Haven't tried it for Rap God yet, could work possibly since it's spoken. I wonder how the pace affects it.

You could try running it locally if you want, there's the https://github.com/SwagLyrics/autosynch/tree/umx-autosynch branch too that uses an improved isolation algorithm.

**Comment by aadibajpai** [comment]
@urmilshroff, btw there are a few samples linked in the readme using the master branch, and there's https://www.youtube.com/watch?v=Ro8tUwWZtu4 that uses the actual spotify music for Finesse
